language: node_js
node_js:
  - '11'
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
cache:
  yarn: true
notifications:
  email: false
script:
  - npm build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "mr_squall"
  - git config --local user.email "squalfot@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $ENCRYPTED_GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true
